apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiuru-admin-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: waiuru-admin-external
  strategy:
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: waiuru-admin-external
    spec:
      containers:
        - name: waiuru-admin-external
          image: gcr.io/waiuru-376612/waiuru-admin-external:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /en-US
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10