apiVersion: v1
kind: Service
metadata:
  name: waiuru-admin-external-service
spec:
  ports:
    - protocol: TCP
      port: 60099
      targetPort: 3000
  type: NodePort
  selector:
    app.kubernetes.io/name: waiuru-admin-external

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waiuru-admin-external-service-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lb-develop-waiuru-admin-external
    networking.gke.io/managed-certificates: waiuru-managed-cert-admin-external-new
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: waiuru-admin-external-service
                port:
                  number: 60099